TeamTwoBe/Models/Sale.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace TeamTwoBe.Models
{
    public class Sale
    {
        public int ID { get; set; }
        [Required]
        public Card Card { get; set; }
        [Required(ErrorMessage = "Price is required")]
        public float Price { get; set; }

        [Required]
        [Display(Name = "Card Condition")]
        public Condition CardCondition { get; set; }

        [Required]
        [Display(Name = "Card grade")]
        public Grade CardGrade { get; set; }

        [Display(Name = "Auction")]
        public bool ForAuction { get; set; }
        public User Buyer { get; set; }
        [Required]
        public User Seller { get; set; }
        //Starts as false. If true, uses the purchaseVerifiedCard function from Stripe API.
        public bool IsVerified { get; set; }
        //Starts as fasle. Changes to true if purchaseCard or purchaseVerifiedCard has been clicked.
        public bool IsSold { get; set; }
        public DateTime UploadDate { get; set; }
        public List<User> Shopper { get; set; }
        public List<User> Watcher { get; set; }
    }
}

TeamTwoBe/Controllers/SalesController.cs
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using TeamTwoBe.Models;
using TeamTwoBe.ViewModels;
using TeamTwoBe.Views.ViewModels;

namespace TeamTwoBe.Controllers
{
    public class SalesController : Controller
    {
        private Context db = new Context();

        HttpClient yugiohApi = new HttpClient()
        {
            BaseAddress = new Uri("https://db.ygoprodeck.com/api/")
        };

        HttpClient yugiohPriceApi = new HttpClient()
        {
            BaseAddress = new Uri("http://yugiohprices.com/api/")
        };
        public bool checkCookie() //check if same ipaddress
        {
            string userid = string.Empty;
            if (Request != null)
            {
                if (Request.Cookies["userid"] != null)
                {
                    var address = Request.UserHostAddress;
                    userid = Request.Cookies["userid"].Value;
                    User user = db.Users.Include("UserLevel").Include("ShoppingCart").Where(x => x.cookie == userid).FirstOrDefault();
                    if (user != null)
                    {
                        Session["UserID"] = user.ID;
                        Session["Username"] = user.Username;
                        Session["UserPic"] = user.DisplayPicture;
                        Session["ShoppingCart"] = user.ShoppingCart.Count();
                        Session["AccountLevel"] = user.UserLevel.ID.ToString();
                    }
                    return true;
                }
            }
            return false;
        }
        public ActionResult Index()
        {
            checkCookie();
            UsersController uc = new UsersController();
            List<Sale> li = new List<Sale>();
            foreach (var i in db.Sales.Include("Card.Cardtype").Include("Watcher").Include("CardCondition").Include("CardGrade").Include("Seller.UserLevel").Where(x => x.Seller.UserLevel.ID == 1 & x.IsSold == false))
            {
                li.Add(i);
            }
            foreach (var i in db.Sales.Include("Card.Cardtype").Include("Watcher").Include("CardCondition").Include("CardGrade").Include("Seller.UserLevel").Where(x => x.Seller.UserLevel.ID == 3 & x.IsSold == false))
            {
                li.Add(i);
            }
            foreach (var i in db.Sales.Include("Card.Cardtype").Include("Watcher").Include("CardCondition").Include("CardGrade").Include("Seller.UserLevel").Where(x => x.Seller.UserLevel.ID == 2 & x.IsSold == false))
            {
                li.Add(i);
            }
            if (Session["UserID"] == null)
            {
                Session["UserID"] = 0;
            }
            return View(li);
        }

        public ActionResult MyListings(int? id)
        {
            checkCookie();
            List<Sale> li = new List<Sale>();
            ListCardListSale vm = new ListCardListSale()
            {
                Sales = li,
                Users = new List<User>(),
            };
            if (Session["UserID"] == null)
            {
                Session["UserID"] = 0;
            }
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            foreach (var i in db.Sales.Include("Card.Cardtype").Include("Watcher").Include("CardCondition").Include("CardGrade").Include("Seller.UserLevel").Where(x => x.Seller.ID == id & x.IsSold == false))
            {
                li.Add(i);
                vm.Users.Add(i.Seller);
            }
            vm.Sales = li;
            return View(vm);
        }

        [HttpPost]
        public async Task<ActionResult> apiPrice(string dropboxvalue)
        {
            checkCookie();
            if (Session["userID"] == null)
            {
                return RedirectToAction("login", "users");
            }
            if (Session["UserID"].ToString() == "0")
            {
                return RedirectToAction("login", "users");
            }
            ViewBag.Conditions = new SelectList(db.Conditions, "ID", "CardCondition");
            ViewBag.Grades = new SelectList(db.Grades, "ID", "Grading");

            HttpResponseMessage resp = await yugiohPriceApi.GetAsync($"get_card_prices/{dropboxvalue}");
            if (resp.IsSuccessStatusCode)
            {
                var rsp = await resp.Content.ReadAsStringAsync();

                var li = JObject.Parse(rsp).ToObject<RootObject>();

                SaleConditionGradeVM salevm = new SaleConditionGradeVM()
                {
                    fix = true,
                    MyCard = dropboxvalue,
                    MyDatum = new List<Datum>(),
                    MyCard1 = "",
                };

                foreach (var i in li.data)
                {
                    if (i.price_data.status == "success")
                    {
                        Card card = new Card()
                        {
                            apiID = $"{dropboxvalue} {i.print_tag} {i.rarity}",
                            name = dropboxvalue,
                            rarity = i.rarity,
                            print_tag = i.print_tag,
                            Cardtype = db.CardTypes.Find(1),
                            image_url = "http://www.ygo-api.com/api/Images/cards/" + dropboxvalue,
                            average = i.price_data.data.prices.average,
                            high = i.price_data.data.prices.high,
                            low = i.price_data.data.prices.low,
                        };
                        if (db.Cards.Where(x => x.name == dropboxvalue).FirstOrDefault() == null)
                        {
                            db.Cards.Add(card);
                        }
                        salevm.MyDatum.Add(i);
                    }
                }
                db.SaveChanges();
                Card cd = db.Cards.Where(x => x.name == dropboxvalue).FirstOrDefault();
                salevm.MyCard1 = cd.name;


                return View("Create", salevm);
            }
            SaleConditionGradeVM salev = new SaleConditionGradeVM();
            return View("Create", salev);
        }

        public ActionResult Details(int? id)
        {
            checkCookie();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Session["View"] = "SaleDetail";
            Sale sale = db.Sales.Find(id);
            if (sale == null)
            {
                return HttpNotFound();
            }
            return View(sale);
        }

        public async Task<ActionResult> Create(int? id)
        {
            checkCookie();
            ViewBag.Conditions = new SelectList(db.Conditions, "ID", "CardCondition");
            ViewBag.Grades = new SelectList(db.Grades, "ID", "Grading");

            //Stops anyone from creating a new sale if they are not logged in as a valid user. ~Joe
            if (Session["userID"] == null)
            {
                return RedirectToAction("login", "users");
            }
            if (Session["UserID"].ToString() == "0")
            {
                return RedirectToAction("login", "users");
            }

            Session["View"] = "SaleCreate";

            SaleConditionGradeVM salevm = new SaleConditionGradeVM();
            if (id != null)
            {
                Card card = db.Cards.Find(id);
                if (card != null)
                {
                    salevm.MyCard = card.name;
                }
            }
            HttpResponseMessage response = await yugiohApi.GetAsync($"v4/cardinfo.php?");
            if (response.IsSuccessStatusCode)
            {
                var rsp = await response.Content.ReadAsStringAsync();

                rsp = rsp.Substring(1, rsp.Length - 2);
                List<Card> li = JArray.Parse(rsp).ToObject<List<Card>>();
                List<Card> li2 = new List<Card>();
                foreach (var i in li)
                {
                    if (li2.Where(x => x.name == i.name).FirstOrDefault() == null)
                    {
                        li2.Add(i);
                    }
                }

                salevm.MyCards = li2;
                salevm.fix = false;
                return View(salevm);
            }
            salevm.fix = false;
            return View(salevm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Price,ForAuction")] SaleConditionGradeVM sale, string dropboxvalue, string Conditions, string Grades)
        {
            checkCookie();
            if (ModelState.IsValid)
            {
                Card card = db.Cards.Where(x => x.apiID == dropboxvalue).FirstOrDefault();
                Grade grade = db.Grades.Find(Convert.ToInt32(Grades));
                Condition condition = db.Conditions.Find(Convert.ToInt32(Conditions));
                User user = db.Users.Find(Session["UserID"]);

                Sale MySale = new Sale()
                {
                    Card = card,
                    Buyer = null,
                    CardCondition = condition,
                    CardGrade = grade,
                    ForAuction = sale.ForAuction,
                    ID = sale.ID,
                    Seller = user,
                    Price = sale.Price,
                    IsSold = false,
                    UploadDate = DateTime.Now.Date,
                };

                db.Sales.Add(MySale);
                var li = db.Users.Include("Watchlist").Include("Wishlist").Where(x => x.Wishlist.Any(z => z.ID == card.ID)).ToList();
                foreach (var i in li)
                {
                    Notification notify = new Notification()
                    {

TeamTwoBe/Views/Sales/Create.cshtml
@model TeamTwoBe.Views.ViewModels.SaleConditionGradeVM

@{
    ViewBag.Title = "New Sale";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o" crossorigin="anonymous"></script>
    <script type="text/javascript" src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/lozad/dist/lozad.min.js"></script>
</head>
<body>
    <div style="display:flex; width:80%">
        <div id="create-container" class="form-horizontal">
            <h2 id="create-title" style="text-align:right; margin:160px auto 30px"><b>NEW SALE</b></h2>

            <div class="form-group">
                @if (Model.fix == false)
                {
                    <label title="Find and search card sdfsdfsto find your cards set." class="control-label col-md-12">Card name</label>
                    <div class="col-md-12">
                        @using (Html.BeginForm("apiPrice", "Sales", FormMethod.Post, new { @id = "card-search" }))
                        {
                            <input value="@Model.MyCard" id="dropbox" list="CardList" type="text" placeholder="Search card to find set." name="dropboxvalue" />
                            <input type="submit" value="Search">
                        }
                    </div>
                }
                @if (Model.MyDatum != null)
                {
                    <datalist id="CardList">
                        @foreach (var i in Model.MyDatum)
                        {
                            <option value="@Model.MyCard @i.print_tag @i.rarity"></option>
                        }
                    </datalist>
                }
                else
                {
                    if (Model.MyCards != null)
                    {
                        <datalist id="CardList">
                            @foreach (var i in Model.MyCards)
                            {
                                <option value="@i.name"></option>
                            }
                        </datalist>
                    }
                }
            </div>
            @using (Html.BeginForm("Create", "Sales", FormMethod.Post, new { @id = "card-search" }))
            {
                if (Model.fix == true)
                {
                    <div class="form-group has-danger">
                        <label data-toggle="tooltip" data-placement="right" data-title="Find and search card to find your cards set." title="Find and search card to find your cards set." class="control-label col-md-12">Card name</label>
                        <div class="col-md-12">
                            <input class="form-control is-invalid" value="@Model.MyCard1" id="dropbox2" list="CardList" type="text" name="dropboxvalue" />
                        </div>
                        <div id="changeMe" class="invalid-feedback">Please select a card from the list!</div>
                    </div>
                }

                if (Model.MyDatum != null)
                {
                    <script>
                $(document).ready(function () {
                    $("#dropbox2").change(function () {
                        var model = @Html.Raw(Json.Encode(Model));
                        var li = $("datalist > option");
                        var name = $("#dropbox2");
                        var i;
                        for (i = 0; i < li.length; i++) {
                            if (name[0].value == li[i].value) {
                                $("#dropbox2").attr("class", "form-control is-valid");
                                $("#changeMe").attr("class", "valid-feedback");
                                $("#changeMe").html("Success!");
                                var myNode = document.getElementById("price-info");
                                while (myNode.firstChild) {
                                    myNode.removeChild(myNode.firstChild);
                                }
                                var heading = document.createElement('h4');
                                var plow = document.createElement('p');
                                var paverage = document.createElement('p');
                                var phigh = document.createElement('p');
                                heading.append("Price info ($USD)");
                                plow.append("Low: $" + model.MyDatum[i].price_data.data.prices.low);
                                paverage.append("Average: $" + model.MyDatum[i].price_data.data.prices.average);
                                phigh.append("High: $" + model.MyDatum[i].price_data.data.prices.high);
                                myNode.append(heading);
                                myNode.append(plow);
                                myNode.append(paverage);
                                myNode.append(phigh);
                                break;
                            }
                            else {
                                $("#dropbox2").attr("class", "form-control is-invalid");
                                $("#changeMe").attr("class", "invalid-feedback");
                                $("#changeMe").html("Please select a card from the list!");
                                var myNode = document.getElementById("price-info");
                                while (myNode.firstChild) {
                                    myNode.removeChild(myNode.firstChild);
                                }
                            }
                        }
                    });
                });
            /**/</script>
                }

                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    <label class="control-label col-md-12">Price</label>
                    <div class="col-md-12">
                        @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control", @id = "pricetb" } })
                        @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger", @name = "Price" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.MySale.CardCondition, htmlAttributes: new { @class = "control-label col-md-12" })
                    <div class="col-md-12">
                        @Html.DropDownList("Conditions", null, "Choose Condition", new { @id = "pricetb" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.MySale.CardGrade, htmlAttributes: new { @class = "control-label col-md-12" })
                    <div class="col-md-12">
                        @Html.DropDownList("Grades", null, "Choose Grade", new { @id = "pricetb" })
                    </div>
                </div>
                <div style="display:flex">
                    <div style="width:55%; margin-top:20px">
                        <div class="form-group row">
                            @Html.LabelFor(model => model.MySale.ForAuction, htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="checkbox col-mid-2">
                                @Html.EditorFor(model => model.ForAuction)
                                @Html.ValidationMessageFor(model => model.MySale.ForAuction, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-12">
                                <input style="width:80%; margin:0 auto" id="submit-btn" onclick="loading()" type="submit" value="Create" class="btn btn-lg btn-default" />
                            </div>
                        </div>
                    </div>
                    <div style="width:45%" id="price-info">
                    </div>
                </div>
            }
        </div>
        <div style="width:30%">
            @if (Model.MyDatum != null)
            {
                if (Model.MyCards != null)
                {
                    <a><div style="margin:227px auto; width:330px" data-tilt data-tilt-glare="true"><img loading="auto" height="485" class="lozad" src="~/Properties/blank.jpg" data-src="@Model.MyCards[0].image_url" /></div></a>
                }
            }
            else
            {
                <div style="display:inline-block;"><img style="margin:227px auto" height="485" src="~/Properties/blank.jpg" /></div>
            }
        </div>
    </div>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/vanilla-tilt/1.7.0/vanilla-tilt.babel.min.js"></script>
    <script type="text/javascript" src="~/Scripts/lazyloading.js"></script>
    <script type="text/javascript" src="~/Scripts/lazyloading2.js"></script>
    <script src="https://code.jquery.com/jquery-3.1.0.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/lozad/dist/lozad.min.js"></script>
</body>

TeamTwoBe/Views/Sales/Edit.cshtml
@model TeamTwoBe.Models.Sale

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Sale</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ForAuction, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.ForAuction)
                    @Html.ValidationMessageFor(model => model.ForAuction, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

TeamTwoBe/Views/Sales/MyListings.cshtml
@model TeamTwoBe.ViewModels.ListCardListSale
@{
    ViewBag.Title = "Listings";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<body>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o" crossorigin="anonymous"></script>
    <script type="text/javascript" src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/lozad/dist/lozad.min.js"></script>

    <div id="base">
        @if (Model.Sales.Count > 0)
        {

            if (Model.Sales[0].Seller.ID.ToString() == Session["UserID"].ToString())
            {
                <div style="margin:auto">
                    <div style="position:relative; display:flex; margin:auto; max-width:1380px;">
                        <h3 style="margin:0 auto 10px">My Listings</h3>
                        <a style="height:20%; color:#3ea6ff;">@Html.ActionLink("New listing", "Create", "Sales", new { }, new { @id = "addlisting", @onclick="loading()" })</a>
                    </div>
                </div>
            }
            else
            {
                <div style="display:flex">
                    <h3 id="sales" style="margin:0 auto 10px">@Model.Sales[0].Seller.Username's listings</h3>
                </div>
            }
            <div id="AllCards" class="container">
                <div class="row">
                    @foreach (var item in Model.Sales)
                    {
                        <div class=" lozad" id="CardGrid" data-tilt data-tilt-glare="true">
                            <div id="Card">
                                <div data-toggle="modal" data-target="#@item.ID" id="CardImage">
                                    <a><div data-tilt data-tilt-glare="true" style="display:inline-block;"><img height="313" width="215" class="lozad" src="~/Properties/blank.jpg" data-src="@item.Card.image_url" /></div></a>
                                </div>
                                <div id="DetailGrid">
                                    <div id="Detail">
                                        <a><p id="CardName">@item.Card.name @item.Card.print_tag</p></a>
                                        <div>
                                            <a id="seller" onclick="loading()" href="/Users/Profile/@item.Seller.ID">@item.Seller.Username</a>
                                            <p id="watchcount">@item.Watcher.Count watchers - @item.UploadDate.ToString("dd/MM/yyyy")</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div id="@item.ID" class="modal fade" role="dialog">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <div id="modal-header1">
                                            <h4 style="text-align:center;" class="modal-title">@item.Card.name</h4>
                                        </div>
                                    </div>
                                    <div class="modal-body">
                                        <div style="display:flex;">
                                            <div id="modalDetails1">
                                                <a><div data-tilt data-tilt-glare="true" style="display:inline-block;"><img height="415" width="275" class="lozad" src="~/Properties/blank.jpg" data-src="@item.Card.image_url" /></div></a>
                                            </div>
                                            <div id="modalDetails">
                                                <p><b>Card Type:</b> @item.Card.Cardtype.Name</p>
                                                <p><b>Card Set:</b> @item.Card.print_tag</p>
                                                <p><b>Rarity:</b> @item.Card.rarity</p>
                                                <h4>Price Info (USD based):</h4>
                                                <p><b>Low:</b> @item.Card.low.ToString("c2") </p>
                                                <p><b>Average:</b> @item.Card.average.ToString("c2") </p>
                                                <p><b>High:</b> @item.Card.high.ToString("c2") </p>
                                                <p><b>This Sale Price (NZD):</b> @item.Price.ToString("c2") </p>
                                                <p><b>Grade:</b> @item.CardGrade.Grading <b>Condition:</b> @item.CardCondition.CardCondition</p>
                                                <p><b>Username: </b>@Html.ActionLink(item.Seller.Username, "Profile", "Users", new { id = item.Seller.ID }, new { @class = "Active", @onclick="loading()" })</p>
                                                @if (item.Seller.ID.ToString() == Session["UserID"].ToString())
                                                {
                                                    <a>@Html.ActionLink("Edit Listing", "editListing", new { id = item.ID }, new { @class = "btn btn-primary", @onclick="loading()" })</a>
                                                    <a id="modalDetails1">@Html.ActionLink("Remove Listing", "removeListing", new { id = item.ID }, new { @class = "btn btn-default", @onclick="loading()" })</a>
                                                }
                                                else
                                                {
                                                    <a>@Html.ActionLink("Add to Watchlist", "addToWatchlist", "Profile", new { id = item.ID }, new { @class = "btn btn-primary", @onclick="loading()" })</a>
                                                    <a id="modalDetails1">@Html.ActionLink("Add to Shopping cart", "addShoppingcart", "Profile", new { id = item.ID }, new { @class = "btn btn-default", @onclick="loading()" })</a>
                                                }
                                            </div>
                                        </div>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        }
        else
        {
            <div style="margin:auto">
                <div style="position:relative; display:flex; margin:auto; max-width:1380px;">
                    <h3 style="padding-left:15px;">My Listings</h3>
                    <a style="height:20%; color:#3ea6ff;">@Html.ActionLink("New listing", "Create", "Sales", new { }, new { @id = "addlisting", @onclick="loading()" })</a>
                </div>
            </div>
        }
    </div>


    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/vanilla-tilt/1.7.0/vanilla-tilt.babel.min.js"></script>
    <script type="text/javascript" src="~/Scripts/lazyloading.js"></script>
    <script type="text/javascript" src="~/Scripts/lazyloading2.js"></script>
    <script src="https://code.jquery.com/jquery-3.1.0.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/lozad/dist/lozad.min.js"></script>
</body>